# Generated by Django 3.1 on 2020-09-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaRelacionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacao', models.CharField(max_length=50, verbose_name='problema relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor')),
                ('problema', models.TextField(verbose_name='problema')),
                ('situacao', models.IntegerField(verbose_name='situacao')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.problemarelacionado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
