# Generated by Django 3.1 on 2020-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_problemarelacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='situacao',
            field=models.IntegerField(default=1, verbose_name='situacao'),
        ),
    ]
