# Generated by Django 3.1 on 2020-09-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20200909_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='pr',
            new_name='relacao',
        ),
    ]
