# Generated by Django 3.1 on 2020-09-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_auto_20200909_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='user',
        ),
    ]
