# Generated by Django 3.1 on 2020-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_remove_chamado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemarelacionado',
            name='relacao',
            field=models.CharField(default=1, max_length=50, verbose_name='problema relacionado'),
        ),
    ]
