# Generated by Django 3.1 on 2020-09-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_auto_20200909_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chamados.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemarelacionado',
            name='relacao',
            field=models.CharField(max_length=50, verbose_name='problema relacionado'),
        ),
    ]
