# Generated by Django 3.1 on 2020-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_auto_20200910_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apelido',
            field=models.CharField(default=1, max_length=50, verbose_name='apelido'),
            preserve_default=False,
        ),
    ]
