# Generated by Django 3.1 on 2020-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_customuser_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='comentario',
            field=models.TextField(null=True, verbose_name='comentario'),
        ),
    ]
