# Generated by Django 3.1 on 2020-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_auto_20200918_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='comentario',
            field=models.TextField(null=True, verbose_name='comentario'),
        ),
    ]
