# Generated by Django 3.1.1 on 2020-09-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_auto_20200918_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situ', models.CharField(max_length=100, verbose_name='situacao')),
            ],
        ),
        migrations.AlterField(
            model_name='chamado',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamados.situacao'),
        ),
    ]
