# Generated by Django 3.1.1 on 2020-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0014_auto_20200922_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='situacao',
            field=models.IntegerField(default=1, verbose_name='situacao'),
        ),
    ]
