# Generated by Django 3.1.1 on 2020-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0015_auto_20200922_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='situacao',
        ),
    ]
