# Generated by Django 3.1.1 on 2020-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0016_remove_chamado_situacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Situacao',
        ),
        migrations.AddField(
            model_name='chamado',
            name='situacao',
            field=models.IntegerField(default=1, verbose_name='situacao'),
        ),
    ]
