# Generated by Django 3.1.1 on 2020-09-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0018_remove_chamado_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situ', models.CharField(max_length=100, verbose_name='situacao')),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chamados.situacao'),
            preserve_default=False,
        ),
    ]
