# Generated by Django 3.1.1 on 2020-09-22 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0019_auto_20200922_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chamados.situacao'),
        ),
    ]
