# Generated by Django 3.1.1 on 2020-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0020_auto_20200922_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='datahora_aberto',
            field=models.DateTimeField(null=True, verbose_name='datahora_aberto'),
        ),
    ]
