# Generated by Django 3.1.1 on 2020-09-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0022_chamado_datahora_fechado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='datahora_andamento',
            field=models.DateTimeField(null=True, verbose_name='datahora_andamento'),
        ),
    ]
